export const PLAYER_STATUS = {
  STANDING_OWN: 0,
  WALKING_OWN: 1,
  DIVING_OWN: 2,
  SWIMMING_OWN: 3,
  ATTACKING_OWN: 4,

  STANDING_SPACE: 5,
  WALKING_SPACE: 6,
  DIVING_SPACE: 7,
  SWIMMING_SPACE: 8,
  ATTACKING_SPACE: 9,

  STANDING_ENEMY: 10,
  WALKING_ENEMY: 11,
  DIVING_ENEMY: 12,
  SWIMMING_ENEMY: 13,
  ATTACKING_ENEMY: 14,
};