export { getKeyDownState } from './getKeyDownState';
export { getKeyUpState } from './getKeyUpState';
export { getMousePos, calculatePlayerAngle } from './mousePos';
export { updatePlayerPosition } from './updatePlayerPosition';
export { getSplats } from './getSplats';
export { getPlayerStatus } from './getPlayerStatus';
export { getPlayerSpeed } from './getPlayerSpeed';
export { getInkAmount } from './getInkAmount';
export { getLineIntersection } from './getLineIntersection';
export { checkFieldCollision,  checkPlayerCollision} from './checkCollision';
export { getGameResult} from './getGameResult';